-- P0 Step 5C.56 — the system must be able to hold a SECOND video provider.
--
-- On 2026-07-27 the Grok account hit a weekly limit. Eleven submissions were accepted and produced nothing,
-- and there is no other way to make a clip: `provider` on generation_jobs is pinned by
--     CHECK (provider = 'GROK')
-- so a job for any other provider cannot be inserted at all. One provider reaching its limit stops the whole
-- factory, and the owner has now added a Google Veo 3 account precisely so that it does not.
--
-- The constraint is not dropped, it is widened to a named allow-list. That keeps what it was actually for —
-- a typo or a caller inventing a provider string still fails loudly at the database — while letting a second
-- REAL provider exist. Adding a third is a one-line migration, which is the right amount of friction: every
-- provider needs an actuator, an account, a lease lane and a ledger before it means anything.
--
-- GOOGLE_VEO is the account the owner enrolled (Google AI Ultra, driven through the browser like Grok, on the
-- same Cloak daemon and the same tunnel lease). No job uses it yet: this migration only makes one expressible.
--
-- Existing rows are untouched — every one of the 75 jobs on record is GROK and stays GROK.

-- The old constraint was written inline, so its name was generated by Postgres rather than chosen. Find it by
-- what it DOES instead of guessing what it was called: a named drop that silently matches nothing would leave
-- the pin in place and this migration would report success while changing nothing.
DO $$
DECLARE c_name TEXT;
BEGIN
  SELECT con.conname INTO c_name
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
   WHERE rel.relname = 'generation_jobs'
     AND con.contype = 'c'
     AND pg_get_constraintdef(con.oid) ILIKE '%provider%'
     AND pg_get_constraintdef(con.oid) ILIKE '%GROK%'
     AND pg_get_constraintdef(con.oid) NOT ILIKE '%GOOGLE_VEO%'
   LIMIT 1;
  IF c_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE generation_jobs DROP CONSTRAINT %I', c_name);
  END IF;
END $$;

ALTER TABLE generation_jobs DROP CONSTRAINT IF EXISTS generation_jobs_provider_allowed;

ALTER TABLE generation_jobs
  ADD CONSTRAINT generation_jobs_provider_allowed
  CHECK (provider IN ('GROK', 'GOOGLE_VEO'));
